TESTING=false

JAVA_FOUND=false
JAVA_VERSION_VALID=false
JAVA_VERSION=
JAVA_PATH=/usr/lib/jvm/jre1.8.0_73/bin/java
JAVA_HOME=/usr/lib/jvm/jre1.8.0_73
export JAVA_HOME

RRE_FOUND=false
RRE_VERSION_VALID=false
RRE_VERSION=
RRE_PATH=/usr/lib64/R/bin/R

RSERVE_FOUND=false
RSERVE_PATH=

JAVA_REQUIRED_VERSION=1.7_13
JAVA_REQUIRED_VERSION8=1.8_31
RSERVE_REQUIRED_VERSION=7.4.2
RRE_REQUIRED_VERSION=8.0
R_REQUIRED_VERSION=3.2.2

DEPLOYR_VERSION=8.0.0
